### ISSUE TITLE
ApiException metadata not decoded

### ISSUE THREAD

**Issue by phoenix1337** [googleads/google-ads-php#182]
When an ApiException with binary data is recevied, it's not decoded and the exception only shows Unknown binary data.

```
{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": "google.ads.googleads.v2.errors.googleadsfailure-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "grpc-status-details-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "request-id",
            "data": "8_Fy_LiK70-DQSNfR972Wg"
        }
    ]
}
```

Instead, the libary should decode this data so it's easier to understand why a request failed.

The method i used in this case is '\Google\Ads\GoogleAds\V2\Services\Gapic\GoogleAdsServiceGapicClient::search' with an invalid field.

**Comment by Raibaz** [comment]
Can you please provide the GAQL query you are executing? 

I just tried with the following query:

```
SELECT campaign.id, campaign.name, foo FROM campaign ORDER BY campaign.id
```

And here is the response I got:

```
ApiException was thrown with message '{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": 0,
            "data": "type.googleapis.com\/google.ads.googleads.v2.errors.GoogleAdsFailure"
        },
        {
            "@type": 0,
            "data": [
                {
                    "errorCode": {
                        "queryError": "UNRECOGNIZED_FIELD"
                    },
                    "message": "Unrecognized field in the query: 'foo'."
                }
            ]
        }
    ]
}'.
```

Also, how are you trying to parse the exception message?

**Comment by phoenix1337** [comment]
The GAQL query to reproduce is:

`
SELECT campaign.id, campaign.status, aa FROM campaign WHERE campaign.status IN ('ENABLED','PAUSED')
`

I get the same result when using the query you used.

It does not matter if I do error handling at all. If I let it bubble up to the console (I use Symfony), the message show is:

```
[Google\ApiCore\ApiException (3)]
  {
      "message": "Request contains an invalid argument.",
      "code": 3,
      "status": "INVALID_ARGUMENT",
      "details": [
          {
              "@type": "google.ads.googleads.v2.errors.googleadsfailure-bin",
              "data": "<Unknown Binary Data>"
          },
          {
              "@type": "grpc-status-details-bin",
              "data": "<Unknown Binary Data>"
          },
          {
              "@type": "request-id",
              "data": "CWfxslxpFV2L1o9yP-b7Xg"
          }
      ]
  }
```

When i dump the complete exception (with the Symfony vardumper), the result is:

```
Google\ApiCore\ApiException^ {#1628
  -status: "INVALID_ARGUMENT"
  -metadata: array:3 [
    "google.ads.googleads.v2.errors.googleadsfailure-bin" => array:1 [
      0 => """
        \n
        ,\n
        \x02( \x12&Unrecognized field in the query: 'aa'.
        """
    ]
    "grpc-status-details-bin" => array:1 [
      0 => """
        \x08\x03\x12%Request contains an invalid argument.\x1Au\n
        Ctype.googleapis.com/google.ads.googleads.v2.errors.GoogleAdsFailure\x12.\n
        ,\n
        \x02( \x12&Unrecognized field in the query: 'aa'.
        """
    ]
    "request-id" => array:1 [
      0 => "5Rrc6jQpZExC3DPdJ_Hh4w"
    ]
  ]
  -basicMessage: "Request contains an invalid argument."
  #message: """
    {\n
        "message": "Request contains an invalid argument.",\n
        "code": 3,\n
        "status": "INVALID_ARGUMENT",\n
        "details": [\n
            {\n
                "@type": "google.ads.googleads.v2.errors.googleadsfailure-bin",\n
                "data": "<Unknown Binary Data>"\n
            },\n
            {\n
                "@type": "grpc-status-details-bin",\n
                "data": "<Unknown Binary Data>"\n
            },\n
            {\n
                "@type": "request-id",\n
                "data": "5Rrc6jQpZExC3DPdJ_Hh4w"\n
            }\n
        ]\n
    }
    """
  #code: 3
  #file: "./vendor/google/gax/src/ApiException.php"
  #line: 139
  trace: {
    ./vendor/google/gax/src/ApiException.php:139 { …}
    ./vendor/google/gax/src/ApiException.php:91 { …}
    ./vendor/google/gax/src/Transport/GrpcTransport.php:251 { …}
    ./vendor/guzzlehttp/promises/src/Promise.php:246 { …}
    ./vendor/guzzlehttp/promises/src/Promise.php:223 { …}
    ./vendor/guzzlehttp/promises/src/Promise.php:267 { …}
    ./vendor/guzzlehttp/promises/src/Promise.php:225 { …}
    ./vendor/guzzlehttp/promises/src/Promise.php:62 { …}
    ./vendor/google/gax/src/GapicClientTrait.php:592 { …}
    ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V2/Services/Gapic/GoogleAdsServiceGapicClient.php:271 { …}
   ./src/Infrastructure/Persistence/GoogleAdsApi/Service/AbstractService.php:55 {
      › try {
      ›     return $this->getGoogleAdsServiceClient()->search($remoteAccountId, $query);
      › } catch (ApiException $e) {
      arguments: {
        $customerId: xxx
        $query: """
          SELECT campaign.id, campaign.status, aa\n
          FROM campaign \n
          WHERE campaign.status IN ('ENABLED','PAUSED')
          """
      }
    }
    ./src/Infrastructure/Persistence/GoogleAdsApi/Service/CampaignService.php:58 { …}
    ./src/Infrastructure/Persistence/ServiceProxy/Service/CampaignServiceProxy.php:24 { …}
    ./src/Application/Command/PullCampaignStatus/PullCampaignStatusHandler.php:38 { …}
    ./src/Infrastructure/Persistence/GoogleAdsApi/Service/CampaignService.php:58 { …}                                                                                                                                                                                               
    ./src/Infrastructure/Persistence/ServiceProxy/Service/CampaignServiceProxy.php:24 { …}                                                                                                                                                                                          
    ./src/Application/Command/PullCampaignStatus/PullCampaignStatusHandler.php:38 { …}
    ./vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:65 { …}
    ./vendor/symfony/messenger/Middleware/SendMessageMiddleware.php:80 { …}
    ./src/Framework/Messenger/Middleware/SequentialMessageMiddleware.php:32 { …}
    ./vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php:36 { …}
    ./vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php:67 { …}
    ./vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php:39 { …}
    ./vendor/symfony/messenger/Middleware/TraceableMiddleware.php:45 { …}
    ./vendor/symfony/messenger/MessageBus.php:73 { …}
    ./vendor/symfony/messenger/TraceableMessageBus.php:43 { …}
    ./src/Infrastructure/UserInterface/Console/PullCampaignStatusConsole.php:44 { …}
    ./vendor/symfony/console/Command/Command.php:255 { …}
    ./vendor/symfony/console/Application.php:939 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:87 { …}
    ./vendor/symfony/console/Application.php:273 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:73 { …}
    ./vendor/symfony/console/Application.php:149 { …}
    ./bin/console:42 { …}
  }
}
```

Using var_dump, i just get a segmentation fault.

Versions:
- PHP version is 7.3.6 
- centos-release-7-6.1810.2.el7.centos.x86_64
- google/common-protos 1.1
- google/gax 1.0.3
- google/grpc-gcp 0.1.4
- google/protobuf v3.9.0
- googleads/google-ads-php v2.0.0
--

**Comment by fiboknacky** [comment]
Just in case, have you also installed [the grpc extension](https://github.com/googleads/google-ads-php/blob/master/README.md#requirements) as well?

**Comment by phoenix1337** [comment]
Yes. Installed extensions are:

```
[PHP Modules]
amqp
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
grpc
hash
iconv
igbinary
imagick
imap
intl
json
libxml
mbstring
mcrypt
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
protobuf
readline
redis
Reflection
session
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xdebug
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

**Comment by fiboknacky** [comment]
I'm sorry. Are you still faced with this issue?

**Comment by jpuck** [comment]
I can confirm this is still an issue with every exception I've seen. There's extra bits of binary data in the message somehow which prevents the [Serializer from being able to decode the metadata][unknown-data]. You can view the raw metadata property in OP's dump:

> ```
> """
> \n
> ,\n
> \x02( \x12&Unrecognized field in the query: 'aa'.
> """
> ```

the actual error message is buried in there:

> Unrecognized field in the query: 'aa'.

Not sure what's causing those other characters around the message.

Here's a similar example when attempting to create an image ad with an invalid size:

```
   Google\ApiCore\ApiException  : {
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": "google.ads.googleads.v2.errors.googleadsfailure-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "grpc-status-details-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "request-id",
            "data": "5FJ09NdunIhrw1IvfgVKgg"
        }
    ]
}
```

which tells you nothing helpful really. so to work around, we must wrap all mutations in a try/catch to expose the real error message. e.g.

```php
try {
    /** @var MutateAdGroupAdResult[] $results */
    $results = $adGroupAdServiceClient
        ->mutateAdGroupAds($accountId, $operations)
        ->getResults();
} catch (ApiException $exception) {
    var_dump($exception->getMetadata());
}
```

shows the same littering of special characters around the message strings:

> ```
> array:3 [
>   "google.ads.googleads.v2.errors.googleadsfailure-bin" => array:1 [
>     0 => b"""
>       \n
>       h\n
>       \x03À\x02\x05\x12%The image is not of legal dimensions.\x1A\x02*\x00"6\x12\x10\n
>       \n
>       operations\x12\x02\x08\x01\x12\x08\n
>       \x06create\x12\x04\n
>       \x02ad\x12\n
>       \n
>       \x08image_ad\x12\x06\n
>       \x04data
>       """
>   ]
>   "grpc-status-details-bin" => array:1 [
>     0 => b"""
>       \x08\x03\x12%Request contains an invalid argument.\x1A±\x01\n
>       Ctype.googleapis.com/google.ads.googleads.v2.errors.GoogleAdsFailure\x12j\n
>       h\n
>       \x03À\x02\x05\x12%The image is not of legal dimensions.\x1A\x02*\x00"6\x12\x10\n
>       \n
>       operations\x12\x02\x08\x01\x12\x08\n
>       \x06create\x12\x04\n
>       \x02ad\x12\n
>       \n
>       \x08image_ad\x12\x06\n
>       \x04data
>       """
>   ]
>   "request-id" => array:1 [
>     0 => "u2qGGdLJ9fXxRXKjqeTsVw"
>   ]
> ]
> ```

and so `\x03À\x02\x05\x12%The image is not of legal dimensions.\x1A\x02*\x00"6\x12\x10\n` contains the real message we're interested in:

> The image is not of legal dimensions.

[unknown-data]:https://github.com/googleapis/gax-php/blob/4baa6d9fb2c5f13ea46c65133848e99fe0aa5ed5/src/Serializer.php#L190

**Comment by fiboknacky** [comment]
@jpuck To better separate issues, could you tell what you've sent as a query? We can deal with the ad group ad creation later.
And could you tell if you use [C-extension of protobuf](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf)?

**Comment by phoenix1337** [comment]
I am still experiencing the issue.  The message posted by @jpuck is actually the same. It does not matter what you do, every exception has the same problem.

**Comment by jpuck** [comment]
@fiboknacky sorry if my additional data was confusing - it's not a separate issue. It doesn't matter whether it's a query or mutation for any service or resource, all error messages that come back cannot be deserialized by the SDK. To be clear, I have no problem with ad group ad creation, I was just trying to illustrate another example of the OP's problem.

And yes I am using the c extension for both GRPC and protobuf.

**Comment by fiboknacky** [comment]
@phoenix1337 @jpuck 

I've tried to reproduce this issue and just found that it would occur when the failure binary key is not configured properly in [GoogleAdsMetadataTrait](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsMetadataTrait.php#L27).
It should be `google.ads.googleads.v2.errors.googleadsfailure-bin`, not `google.ads.googleads.v1.errors.googleadsfailure-bin`.

I remember vaguely that we had a bug in this line before, which has been resolved for a while ago.
Could you please update to the most recent version and try again?

**Comment by jpuck** [comment]
@fiboknacky I have just upgraded to the latest release of this SDK v2.2.0 and can confirm the issue is not fixed 😞 

If you look at [my output][output], you can see the key is using `google.ads.googleads.v2.errors.googleadsfailure-bin` 

[output]:https://github.com/googleads/google-ads-php/issues/182#issuecomment-556556855

**Comment by fiboknacky** [comment]
Is your `GoogleAdsMetadataTrait` the same as [this](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsMetadataTrait.php#L27)?

**Comment by fiboknacky** [comment]
Closing due to inactivity.

**Comment by phoenix1337** [comment]
This issue is still not resolved. With v3 of the sdk, i am still experiencing the same issue. The trait being used is the same as the one you mentioned.

**Comment by fiboknacky** [comment]
Could you share gRPC, protobuf and gax-php versions that you've installed too?
They can be found in the `composer.lock` file.

**Comment by phoenix1337** [comment]
For the libraries:
`google/grpc-gcp                        0.1.4              gRPC GCP library for channel management                                                                                                                                                                               grpc/grpc                              1.26.1             gRPC library for PHP
google/gax                             1.2.0              Google API Core for PHP
google/protobuf                        v3.11.2            proto library for PHP`

For php exentions:
`php-pecl-protobuf.x86_64                3.11.2-1.el7.remi.7.4      @remi-php74
php-pecl-grpc.x86_64                    1.26.0-1.el7.remi.7.4      @remi-php74
`

**Comment by fiboknacky** [comment]
@phoenix1337  Have you tried using the C extension of gRPC too?
(See the section **Update php.ini** in [this guide](https://grpc.io/docs/quickstart/php/))

**Comment by phoenix1337** [comment]
@fiboknacky 

This are all the php extensions i have enabled:

[PHP Modules]                                                                                                                                                                                                                                                                   amqp                                                                                                                                                                                                                                                                            bcmath                                                                                                                                                                                                                                                                          bz2                                                                                                                                                                                                                                                                             calendar                                                                                                                                                                                                                                                                        Core                                                                                                                                                                                                                                                                            ctype                                                                                                                                                                                                                                                                           curl                                                                                                                                                                                                                                                                            date                                                                                                                                                                                                                                                                            dom                                                                                                                                                                                                                                                                             exif                                                                                                                                                                                                                                                                            fileinfo                                                                                                                                                                                                                                                                        filter                                                                                                                                                                                                                                                                          ftp                                                                                                                                                                                                                                                                             gd                                                                                                                                                                                                                                                                              gettext                                                                                                                                                                                                                                                                         gmp                                                                                                                                                                                                                                                                             grpc                                                                                                                                                                                                                                                                            hash                                                                                                                                                                                                                                                                            horde_lz4                                                                                                                                                                                                                                                                       iconv                                                                                                                                                                                                                                                                           igbinary                                                                                                                                                                                                                                                                        imagick                                                                                                                                                                                                                                                                         imap                                                                                                                                                                                                                                                                            intl                                                                                                                                                                                                                                                                            json                                                                                                                                                                                                                                                                            libxml                                                                                                                                                                                                                                                                          mbstring                                                                                                                                                                                                                                                                        mcrypt                                                                                                                                                                                                                                                                          memcache                                                                                                                                                                                                                                                                        msgpack                                                                                                                                                                                                                                                                         mysqli                                                                                                                                                                                                                                                                          mysqlnd                                                                                                                                                                                                                                                                         openssl                                                                                                                                                                                                                                                                         pcntl                                                                                                                                                                                                                                                                           pcre                                                                                                                                                                                                                                                                            PDO                                                                                                                                                                                                                                                                             pdo_mysql                                                                                                                                                                                                                                                                       Phar                                                                                                                                                                                                                                                                            posix                                                                                                                                                                                                                                                                           protobuf                                                                                                                                                                                                                                                                        readline                                                                                                                                                                                                                                                                        redis                                                                                                                                                                                                                                                                           Reflection                                                                                                                                                                                                                                                                      session                                                                                                                                                                                                                                                                         SimpleXML                                                                                                                                                                                                                                                                       soap                                                                                                                                                                                                                                                                            sockets                                                                                                                                                                                                                                                                         SPL                                                                                                                                                                                                                                                                             standard                                                                                                                                                                                                                                                                        sysvmsg                                                                                                                                                                                                                                                                         sysvsem                                                                                                                                                                                                                                                                         sysvshm                                                                                                                                                                                                                                                                         tidy                                                                                                                                                                                                                                                                            tokenizer                                                                                                                                                                                                                                                                       xml                                                                                                                                                                                                                                                                             xmlreader                                                                                                                                                                                                                                                                       xmlwriter                                                                                                                                                                                                                                                                       Zend OPcache                                                                                                                                                                                                                                                                    zip                                                                                                                                                                                                                                                                             zlib                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [Zend Modules]                                                                                                                                                                                                                                                                  Zend OPcache

Also tried installing grp using pecl instead of yum but still the same issue:

#message: """
  {
	  "message": "Request contains an invalid argument.",
	  "code": 3,
	  "status": "INVALID_ARGUMENT",
	  "details": [
		  {
			  "@type": "google.ads.googleads.v2.errors.googleadsfailure-bin",
			  "data": "<Unknown Binary Data>"
		  },
		  {
			  "@type": "grpc-status-details-bin",
			  "data": "<Unknown Binary Data>"
		  },
		  {
			  "@type": "request-id",
			  "data": "P8V4ljd5jd_Q1mKIFXy2vg"
		  }
	  ]
  }

Content of the trait:

`#message: """
  {
	  "message": "Request contains an invalid argument.",
	  "code": 3,
	  "status": "INVALID_ARGUMENT",
	  "details": [
		  {
			  "@type": "google.ads.googleads.v2.errors.googleadsfailure-bin",
			  "data": "<Unknown Binary Data>"
		  },
		  {
			  "@type": "grpc-status-details-bin",
			  "data": "<Unknown Binary Data>"
		  },
		  {
			  "@type": "request-id",
			  "data": "P8V4ljd5jd_Q1mKIFXy2vg"
		  }
	  ]
  }
`

**Comment by fiboknacky** [comment]
@phoenix1337  I would need your help to dig a bit more.
In [this block](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsExceptionMiddleware.php#L69), an GoogleAdsException object is created using the metadata from the exception.
Could you debug into that block and see what's inside the `$metadata` variable?

**Comment by phoenix1337** [comment]
Content of metadata is (using the symfony var dumper)

`
^ array:3 [                                                                                                                                                                                                                                                                       "google.ads.googleads.v2.errors.googleadsfailure-bin" => array:1 [                                                                                                                                                                                                                0 => """                                                                                                                                                                                                                                                                          \n                                                                                                                                                                                                                                                                              +\n                                                                                                                                                                                                                                                                             \x02( \x12%Unrecognized field in the query: 'a'.                                                                                                                                                                                                                                """                                                                                                                                                                                                                                                                         ]                                                                                                                                                                                                                                                                               "grpc-status-details-bin" => array:1 [                                                                                                                                                                                                                                            0 => """                                                                                                                                                                                                                                                                          \x08\x03\x12%Request contains an invalid argument.\x1At\n                                                                                                                                                                                                                       Ctype.googleapis.com/google.ads.googleads.v2.errors.GoogleAdsFailure\x12-\n                                                                                                                                                                                                     +\n                                                                                                                                                                                                                                                                             \x02( \x12%Unrecognized field in the query: 'a'.                                                                                                                                                                                                                                """                                                                                                                                                                                                                                                                         ]                                                                                                                                                                                                                                                                               "request-id" => array:1 [                                                                                                                                                                                                                                                         0 => "pe0Lm1cPY5e_5XIbdtcgTQ"                                                                                                                                                                                                                                                 ]                                                                                                                                                                                                                                                                             ]
--


`

**Comment by fiboknacky** [comment]
Looking at your dumped values, the GoogleAdsException object is created in the below if clause and thrown, as expected?
If so, I wonder why you ended up getting ApiException instead of GoogleAdsException.

**Comment by phoenix1337** [comment]
Ah right, the difference with the start of this issue is that it is an GoogleAdsException and not an ApiException anymore, but the metadata is still not decoded.

Below the exception with stacktrace.

```
Google\Ads\GoogleAds\Lib\V2\GoogleAdsException^ {#2
        -googleAdsFailure: Google\Ads\GoogleAds\V2\Errors\GoogleAdsFailure^ {#3}
        -status: "INVALID_ARGUMENT"
        -metadata: [
          "google.ads.googleads.v2.errors.googleadsfailure-bin" => [
            """
              \n
              +\n
              \x02( \x12%Unrecognized field in the query: 'a'.
              """
          ],
          "grpc-status-details-bin" => [
            """
              \x08\x03\x12%Request contains an invalid argument.\x1At\n
              Ctype.googleapis.com/google.ads.googleads.v2.errors.GoogleAdsFailure\x12-\n
              +\n
              \x02( \x12%Unrecognized field in the query: 'a'.
              """
          ],
          "request-id" => [
            "0WM2QISAl7XaiqFx-doI7A"
          ]
        ]
        -basicMessage: "Request contains an invalid argument."
        #message: """
          {\n
              "message": "Request contains an invalid argument.",\n
              "code": 3,\n
              "status": "INVALID_ARGUMENT",\n
              "details": [\n
                  {\n
                      "@type": "google.ads.googleads.v2.errors.googleadsfailure-bin",\n
                      "data": "<Unknown Binary Data>"\n
                  },\n
                  {\n
                      "@type": "grpc-status-details-bin",\n
                      "data": "<Unknown Binary Data>"\n
                  },\n
                  {\n
                      "@type": "request-id",\n
                      "data": "0WM2QISAl7XaiqFx-doI7A"\n
                  }\n
              ]\n
          }
          """
        #code: 3
        #file: "./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsExceptionMiddleware.php"
        #line: 110
        trace: {
          ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsExceptionMiddleware.php:110 { …}
          ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsExceptionMiddleware.php:81 { …}
          ./vendor/guzzlehttp/promises/src/Promise.php:203 { …}
          ./vendor/guzzlehttp/promises/src/Promise.php:156 { …}
          ./vendor/guzzlehttp/promises/src/TaskQueue.php:47 { …}
          ./vendor/guzzlehttp/promises/src/Promise.php:234 { …}
          ./vendor/guzzlehttp/promises/src/Promise.php:267 { …}
          ./vendor/guzzlehttp/promises/src/Promise.php:225 { …}
          ./vendor/guzzlehttp/promises/src/Promise.php:62 { …}
          ./vendor/google/gax/src/GapicClientTrait.php:604 { …}
          ./vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V2/Services/Gapic/GoogleAdsServiceGapicClient.php:271 { …}
          ./src/Infrastructure/Persistence/GoogleAdsApi/Service/AbstractService.php:40 {
            Infrastructure\Persistence\GoogleAdsApi\Service\AbstractService->search(?int $remoteAccountId, string $query): PagedListResponse^
            › try {
            ›     return $this->getGoogleAdsServiceClient()->search((string)$remoteAccountId, $query);
            › } catch (\Exception $exception) {
            arguments: {
              $customerId: "xxx"
              $query: """
                SELECT campaign.id, campaign.status, a\n
                FROM campaign \n
                WHERE campaign.status IN ('ENABLED','PAUSED')
                """
            }
          }
          ./src/Infrastructure/Persistence/GoogleAdsApi/Service/CampaignService.php:69 { …}
          ./src/Infrastructure/Persistence/ServiceProxy/Service/CampaignServiceProxy.php:31 { …}
          ./src/Application/Command/PullCampaignStatus/PullCampaignStatusHandler.php:40 { …}
          ./vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:63 { …}
          ./vendor/symfony/messenger/Middleware/SendMessageMiddleware.php:79 { …}
          ./src/Framework/Messenger/Middleware/CommandErrorMiddleware.php:66 { …}
          ./src/Framework/Messenger/Middleware/SequentialMessageMiddleware.php:34 { …}
          ./vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php:34 { …}
          ./vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php:67 { …}
          ./vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php:42 { …}
          ./vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php:37 { …}
          ./vendor/symfony/messenger/Middleware/TraceableMiddleware.php:43 { …}
          ./vendor/symfony/messenger/MessageBus.php:80 { …}
          ./vendor/symfony/messenger/TraceableMessageBus.php:41 { …}
          ./vendor/symfony/messenger/RoutableMessageBus.php:54 { …}
          ./vendor/symfony/messenger/Worker.php:117 { …}
          ./vendor/symfony/messenger/Worker.php:81 { …}
          ./vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:202 { …}
          ./vendor/symfony/console/Command/Command.php:255 { …}
          ./vendor/symfony/console/Application.php:1029 { …}
          ./vendor/symfony/framework-bundle/Console/Application.php:97 { …}
          ./vendor/symfony/console/Application.php:272 { …}
          ./vendor/symfony/framework-bundle/Console/Application.php:83 { …}
          ./vendor/symfony/console/Application.php:148 { …}
          ./bin/console:42 { …}
        }
      }
```

**Comment by fiboknacky** [comment]
Isn't the essential detail already in [`$googleAdsFailure`](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsException.php#L30) of the created GoogleAdsException already?

It contains the list of [`GoogleAdsError`](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V2/Errors/GoogleAdsError.php), which in turn contains the error code and message.

Could you let me know if you're looking for something else?

**Comment by phoenix1337** [comment]
The message shows 'Unknown binary data' so that is not correct? It should be decoded. The metadata is also not showing decoded data.

What I am looking for is that the message contains the decoded binary data from the metadata so I can simply use the message. The message is now missing some essential information about which field is incorrect and that information is in google.ads.googleads.v2.errors.googleadsfailure-bin which is not decoded.

**Comment by fiboknacky** [comment]
> What I am looking for is that the message contains the decoded binary data from the metadata so I can simply use the message. The message is now missing some essential information about which field is incorrect and that information is in google.ads.googleads.v2.errors.googleadsfailure-bin which is not decoded.

The binary data is actually decoded and populated as [$googleAdsFailure](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsException.php#L30) using the key `google.ads.googleads.v2.errors.googleadsfailure-bin`. 
This is done in [this line](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V2/GoogleAdsExceptionMiddleware.php#L75).

The message should be in the `GoogleAdsError` as I mentioned in the previous reply.

It may look confusing when you see the dump because we just want to also include raw metadata when creating `GoogleAdsException` (which inherits from `ApiException`), but again, what's useful is already decoded and stored in the `GoogleAdsFailure`, so you can just focus on using that.
I believe if you fetch the message from `GoogleAdsError`, it will look similar to "Unrecognized field in the query: 'a'".

**Comment by franco104** [comment]
I was just experiencing this same thing. I noticed when i used php with cli it did not decode exception message properly but data was readable in $googleAdsFailure but when i used php apache it decoded the exception message just fine doing same exact call and all was readable. It seems when i do not add extension=grpc.so to php.ini file the message is decoded fine but when it is there the message will not decode and can only be read in $googleAdsFailure. Not sure if this is expected or not. Hopefully this will help someone with issue i had that make their way to this post
This was done using v3

**Comment by fiboknacky** [comment]
@franco104 Can you show what you get when using grpc and not using grpc here too?

**Comment by franco104** [comment]
this is the exception message when extension is not added to php.ini
{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": 0,
            "data": "type.googleapis.com\/google.ads.googleads.v3.errors.GoogleAdsFailure"
        },
        {
            "@type": 0,
            "data": [
                {
                    "errorCode": {
                        "customerClientLinkError": "CLIENT_ALREADY_MANAGED_IN_HIERARCHY"
                    },
                    "message": "The client sending the invitation already has a manager.",
                    "trigger": {
                        "stringValue": ""
                    },
                    "location": {
                        "fieldPathElements": [
                            {
                                "fieldName": "operation"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

this is the exception message when extension is added to php.ini
{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": "google.ads.googleads.v3.errors.googleadsfailure-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "grpc-status-details-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "request-id",
            "data": "J1BicRLi7tS-F3KUYHd7jQ"
        }
    ]
}

Different calls then in the OP but its the exception message that was in question here

**Comment by fiboknacky** [comment]
Can you check what I explained in [this reply](https://github.com/googleads/google-ads-php/issues/182#issuecomment-575025728)?
In GRPC, you probably cannot see the readable dump directly. But all useful information should already be stored `GoogleAdsFailure`.

**Comment by jiezhang917** [comment]
@fiboknacky Thanks! It turned out I'm using both of the grpc.so in php.ini and google/protobuf package. I commented out grpc module in php.ini and now I can see the error messages decoded.

**Comment by GitHubgopinath** [comment]
Hello ,
I am also getting this error 

Google Ads failure details: query_error: Unrecognized fields in the query: 'text_ad_recommendation', 'type'.
