### ISSUE TITLE
ProductCondition Listing Group Filter issues

### ISSUE THREAD

**Issue by usagreatus** [googleads/google-ads-php#838]
**Your client library and Google Ads API versions:**

* Client library version: `v15.1.0`
* Google Ads API version: `V11`
* 
**Your environment:**

* The PHP version: `8.0.20`.
* The name and version of the operating system: `Linux 45b930250aa4 5.10.104-linuxkit`.
* Whether the PHP Extension `protobuf` is used or not: `No`.
* Whether the PHP Extension `grpc` is used or not: `1.46.3`.
* The type of transport being used (`grpc` or `rest`): `grpc`.

**Description of the bug:**
I have problems creating ListingGroupFilter for an Asset Group in Performance Max Campaign via Ads API. I tried creating ListingGroup filter by ProductCondition value *new*. I got a success response but checking it in the google ads ui showed that the filter has value *refurbished*. I then created another product condition filter in goole ads ui with value *new*. And after that did a search query to get listing group filters for the asset group that i am testing on. The response shows the condition value as *2*, which is not a valid value in php sdk enum class ProductCondition. I can't map the response using enum class, cause value is not valid.  Also tried to create a filter with value *used*,  and it fails with error: `Enum value 'UNKNOWN_ENUM_VALUE_ListingGroupFilterProductCondition_5' cannot be used`
Enum class in google ads php sdk: [https://github.com/googleads/google-ads-php/blob/v15.1.0/src/Google/Ads/GoogleAds/V11/Enums/ProductConditionEnum/ProductCondition.php](https://github.com/googleads/google-ads-php/blob/v15.1.0/src/Google/Ads/GoogleAds/V11/Enums/ProductConditionEnum/ProductCondition.php)
**Steps to reproduce:**
Detailed description of the issue and with code samples screenshots:
[https://groups.google.com/g/adwords-api/c/IIIZsibINRI](https://groups.google.com/g/adwords-api/c/IIIZsibINRI)

**Comment by fiboknacky** [comment]
> Whether the PHP Extension protobuf is used or not: No.
Do you mean you use the [C implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf?hl=en#c_implementation) instead?
Could you please provide the protobuf version number?

It seems like [your issue](https://github.com/protocolbuffers/protobuf/pull/9780) is already fixed in protobuf [v21.0](https://github.com/protocolbuffers/protobuf/releases/tag/v21.0), so if you're using this version or higher, the issue should be gone.
If not, please let me know.

**Comment by usagreatus** [comment]
> 

I had no php extension for protobuf, so it was using composer package which was V3.21.1. I installed php protobuf extension:
```                                                                                                                  
# php -r 'print phpversion("protobuf");'
3.21.4# 
```
[https://github.com/protocolbuffers/protobuf/releases](url)

Unfortunately I still have issue with product condition values mismatch

**Comment by fiboknacky** [comment]
Instead of screenshots, could you please copy text over here, so we can take a closer look?
Some screenshots are too small and I cannot see the details inside them clearly.

**Comment by usagreatus** [comment]
> Instead of screenshots, could you please copy text over here, so we can take a closer look? Some screenshots are too small and I cannot see the details inside them clearly.
Sure, I create an instance of ProductCondition, then put it in AssetGroupListingGroupFilter and AssetGroupListingGroupFilterOperation and send operations, which does successful mutate request but in the ads ui the condition is not new but refurbished:
```
$conditionInfo = new ProductCondition();
$conditionInfo->setCondition(ProductConditionEnum::value("PBNEW");
$dimension = new ListingGroupFilterDimension(
    ['product_condition' => $conditionInfo]
);
$assetGroupListingGroupFilter = new AssetGroupListingGroupFilter([
    'resource_name' => ResourceNames::forAssetGroupListingGroupFilter(
        $customerId,
        $assetGroupId,
            $this->tempId
        ),
    'asset_group' => ResourceNames::forAssetGroup($customerId, $assetGroupId),
    'parent_listing_group_filter' => $parentsResourceName,
    'type' => $type,
    'vertical' => ListingGroupFilterVertical::SHOPPING,
    'case_value' => $dimension
]);
```

After this i just go to google ads account and add one more listing group filter by product condition with value new.
and i do search query to get listing group filters:

```
SELECT

asset_group_listing_group_filter.asset_group,
asset_group_listing_group_filter.id,
asset_group_listing_group_filter.parent_listing_group_filter,
asset_group_listing_group_filter.resource_name,
asset_group_listing_group_filter.type,
asset_group_listing_group_filter.vertical,
asset_group_listing_group_filter.case_value.product_type.value,
asset_group_listing_group_filter.case_value.product_type.level,
asset_group_listing_group_filter.case_value.product_item_id.value,
asset_group_listing_group_filter.case_value.product_custom_attribute.value,
asset_group_listing_group_filter.case_value.product_custom_attribute.index,
asset_group_listing_group_filter.case_value.product_condition.condition,
asset_group_listing_group_filter.case_value.product_channel.channel,
asset_group_listing_group_filter.case_value.product_brand.value,
asset_group_listing_group_filter.case_value.product_bidding_category.level,
asset_group_listing_group_filter.case_value.product_bidding_category.id

FROM asset_group_listing_group_filter

WHERE
asset_group_listing_group_filter.asset_group = 'customers/xxxxxxxxxx/assetGroups/xxxxxxxxxxxxx'
```
I get back response with 4 asset group listing group filters: a root one and 3 children with case value ProductCondition. they have values: 3 (this one was created my me via api), 0 - everything else node (also created via api), 2 (this one i created in google ads ui directly, and the enum class doesn't have mapping for it): [https://github.com/googleads/google-ads-php/blob/v15.1.0/src/Google/Ads/GoogleAds/V11/Enums/ProductConditionEnum/ProductCondition.php#L21-L45](url)
so in the enum class when it tries to get name by value it fails validation because there is no mapping to value 2, here: [https://github.com/googleads/google-ads-php/blob/986e0ead76e9d73950f5689474768497a501f592/src/Google/Ads/GoogleAds/V11/Enums/ProductConditionEnum/ProductCondition.php#L58](url)

**Comment by fiboknacky** [comment]
Sorry for the back-and-forth. Could you also share the latest request ID when you ran the above query?
Thanks.

**Comment by usagreatus** [comment]
> Sorry for the back-and-forth. Could you also share the latest request ID when you ran the above query? Thanks.

Hi, yes sure. The request id of the searchStream query: `xgi-kOivunc5gUJrgoE9Hg`

**Comment by fiboknacky** [comment]
Thanks. I cannot find the log from the request ID. When did you run this request?
BTW, could you try using `search` instead of `searchStream`? Unfortunately, due to a limitation, I cannot see the raw response when `searchStream` is used.

**Comment by usagreatus** [comment]
> 



> Thank you. BTW, could you try using `search` instead of `searchStream`? Unfortunately, due to a limitation, I cannot see the raw response when `searchStream` is used.

Yea, I can totally do it. Do you know how to extract the request_id from a search request?

I can see it in [SearchStreamResponse](https://developers.google.com/google-ads/api/reference/rpc/v11/SearchGoogleAdsStreamResponse?hl=en), but don't see it in [SearchResponse](https://developers.google.com/google-ads/api/reference/rpc/v11/SearchGoogleAdsResponse?hl=en)

**Comment by usagreatus** [comment]
> 



> > 
> 
> > Thank you. BTW, could you try using `search` instead of `searchStream`? Unfortunately, due to a limitation, I cannot see the raw response when `searchStream` is used.
> 
> Yea, I can totally do it. Do you know how to extract the request_id from a search request?
> 
> I can see it in [SearchStreamResponse](https://developers.google.com/google-ads/api/reference/rpc/v11/SearchGoogleAdsStreamResponse?hl=en), but don't see it in [SearchResponse](https://developers.google.com/google-ads/api/reference/rpc/v11/SearchGoogleAdsResponse?hl=en)

I figured it out, i had to build client with logger, here are the details of the request:

```
Method: "/google.ads.googleads.v11.services.GoogleAdsService/Search", CustomerId: xxxxxxx, RequestId: "9jOV9G3ksHWQ3E4GvY4YiA"
```

let me know if you need more info.

**Comment by fiboknacky** [comment]
Thank you. I can reproduce the issue using both C and PHP implementations of the protobuf extension, but in a bit different way than yours.
Mine doesn't throw any errors, but the value returned from `$googleAdsRow->getAssetGroupListingGroupFilter()->getCaseValue()->getProductCondition()->getCondition()` is 3 (`NEW`) instead of `REFURBISHED`.

Interestingly, when I call protobuf's `serializeToJsonString()`, it'll output correctly:

```
{"resourceName":"customers/4900036901/assetGroupListingGroupFilters/6449226683~6540088053","id":"6540088053","caseValue":{"productCondition":{"condition":"REFURBISHED"}}}
```

Since our logger uses `serializeToJsonString()`, I think if you make it print details, it'll correctly print `REFURBISHED` too.

I don't have an answer off the top of my head either.
This would take some time because I'd need to touch base with the protobuf team and related teams in order to understand what happens here.

In the meantime, could you share the code where you print the result from `search()` too?

**Comment by usagreatus** [comment]
> (This answer has been edited)
> 
> Thank you, but I cannot reproduce the issue by using both C and PHP implementations of the protobuf extension. Could you try calling `$googleAdsRow->getAssetGroupListingGroupFilter()->getCaseValue()->getProductCondition()->getCondition()` where `$googleAdsRow` is one row when you loop over the result?
> 
> I got something like this and cannot see the value 5 that would break the enum's `name()` method.
> 
> ```
> {"resourceName":"customers/4900036901/assetGroupListingGroupFilters/6449226683~6540088053","id":"6540088053","caseValue":{"productCondition":{"condition":"REFURBISHED"}}}
> ```
> 
> In the meantime, could you share the code where you print the result from `search()` too?
> 
> Right now, it looks like your asset group has three listing group filters: `UNIT_INCLUDED` (the one that has `REFURBISHED` as a product condition), `UNIT_EXCLUDED`, and `SUBDIVISION`.

Hi! Ok, thanks for looking into it. So we get back `REFURBISHED`. But what is the issue here that - in the mutate request i sent it as `NEW` not `REFURBISHED`. I send `NEW` and in ads ui it appears to be `REFURBISHED`. You can see it in the code above i provided, i will paste it here again: 
```
$conditionInfo = new ProductCondition();
$conditionInfo->setCondition(ProductConditionEnum::value("PBNEW"); // <- here it is set to new, and after a successful mutate request i go to ads account, it's not new it's refurbished
$dimension = new ListingGroupFilterDimension(
    ['product_condition' => $conditionInfo]
);
```
i can make a mutate request again and send you the request id if you need it, thank you

**Comment by fiboknacky** [comment]
You used a wrong enum class. The correct one is [ListingGroupFilterProductCondition](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V11/Enums/ListingGroupFilterProductConditionEnum/ListingGroupFilterProductCondition.php). 

In addition, you can do like this:

```
$conditionInfo->setCondition(ListingGroupFilterProductCondition::PBNEW); 
```

**Comment by usagreatus** [comment]
> 



> You used a wrong enum class. The correct one is [ListingGroupFilterProductCondition](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V11/Enums/ListingGroupFilterProductConditionEnum/ListingGroupFilterProductCondition.php).
> 
> In addition, you can do like this:
> 
> ```
> $conditionInfo->setCondition(ListingGroupFilterProductCondition::PBNEW); 
> ```

Oh my, that's true. Everything is good now. Thank you so much!
